plugins:
    - rubocop-minitest
    - rubocop-performance
    - rubocop-rake
    - rubocop-thread_safety

AllCops:
    TargetRubyVersion: '3.2'
    NewCops: enable
    SuggestExtensions: false
    Exclude:
        - 'vendor/**/*'
        - 'tmp/**/*'
        - 'pkg/**/*'

# Metrics are too arbitrary.
Metrics/AbcSize:
    Enabled: false
Metrics/ClassLength:
    Enabled: false
Layout/LineLength:
    Enabled: false
Metrics/MethodLength:
    Enabled: false

# Weird.
Style/FormatStringToken:
    Enabled: false
Style/NumericPredicate:
    Enabled: false

# Trailing commas are good.
Style/TrailingCommaInArguments:
    Enabled: false
Style/TrailingCommaInArrayLiteral:
    Enabled: false
Style/TrailingCommaInHashLiteral:
    Enabled: false

Gemspec/DevelopmentDependencies:
    Enabled: false

# Sometimes it makes sense to have lots of assertions.
Minitest/MultipleAssertions:
    Enabled: false

ThreadSafety/NewThread:
    Exclude:
        - 'test/**/*'

# Iterator yields tuples [network, data], not a hash
Style/HashEachMethods:
    Enabled: false

# Project-specific
Style/Documentation:
    Enabled: false

Style/StringLiterals:
    EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
    Enabled: true

Lint/EmptyClass:
    Exclude:
        - 'lib/maxmind/db/rust.rb'
